### ISSUE TITLE
Refinements

### ISSUE THREAD

**Issue by mmiszy** [typeofweb/schema#16]
Blocked by #45.

**Comment by o-alexandrov** [comment]
Thank you, currently using [zod](https://github.com/colinhacks/zod) because of the built-in `static type inference`, but I enjoy seeing that you developed in pure functions, with ability to import only what's needed.
Unfortunately, zod's drawback is in the size of it, about ~13KB are non tree-shakeable.

It would be great to see how you decide to handle Refinements/Transformations! 👍

**Comment by mmiszy** [comment]
Yeah, one of the project goals was to make it as lightweight as possible, tree-shaking included!

**Comment by mmiszy** [comment]
Request For Comments: https://github.com/typeofweb/schema/issues/45
