### ISSUE TITLE
More benchmarks

### ISSUE THREAD

**Issue by hasparus** [typeofweb/schema#32]
I'm interested how _schema_ compares with _ts-json-validator_, _zod_, and _io-ts_.

When it's feature-ready, getting it featured in https://github.com/moltar/typescript-runtime-type-benchmarks could be beneficial for easy comparison with the 19 libraries already there.

**Comment by mmiszy** [comment]
`zod` is surprisingly slow.
`io-ts` is ~2x as fast as `@typeofweb/schema`.
`ts-json-validator` – didn't compare yet!

There are also other much faster validators on the market: `ajv` and `fastest-validation`. However, we've decided not to include them in the comparison due to the fact they're more _compilers_ than validators (they pre-generate JavaScript code based on validators used). Due to that they either require a build step or they won't work with CSP rules forbidding `eval`.

## Quick benchmark
```
Platform info:
==============
   Darwin 20.2.0 x64
   Node.JS: 14.15.2
   V8: 8.4.371.19-node.17
   Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz × 8
```

| library                 | relative speed | operations per second | avg. operation time |
| ----------------------- | -------------: | --------------------: | ------------------: |
| io-ts@2.2.13            |             0% |       (3,453,591 rps) |      (avg: 0.289μs) |
| @typeofweb/schema@0.4.2 |        -64.82% |       (1,214,973 rps) |      (avg: 0.823μs) |
| mschema@0.5.6           |        -83.31% |         (576,301 rps) |          (avg: 1μs) |
| validator.js@2.0.4      |        -85.94% |         (485,670 rps) |          (avg: 2μs) |
| validate.js@0.13.1      |        -93.30% |         (231,282 rps) |          (avg: 4μs) |
| validatorjs@3.22.1      |        -95.15% |         (167,352 rps) |          (avg: 5μs) |
| joi@17.3.0              |        -96.33% |         (126,595 rps) |          (avg: 7μs) |
| yup@0.32.8              |        -98.10% |          (65,707 rps) |         (avg: 15μs) |
| superstruct@0.13.3      |        -98.14% |          (64,099 rps) |         (avg: 15μs) |
| jsonschema@1.4.0        |        -98.87% |          (38,916 rps) |         (avg: 25μs) |
| parambulator@1.5.2      |        -99.36% |          (22,185 rps) |         (avg: 45μs) |
| zod@1.11.11             |        -99.49% |          (17,509 rps) |         (avg: 57μs) |

**Comment by mmiszy** [comment]
I realized I've made a mistake – schemas used with io-ts was much simpler than the other ones. For example, it didn't validate for length of strings. Updated results:

| library               | relative speed | operations per second | avg. operation time |
| --------------------- | -------------: | --------------------: | ------------------: |
| io-ts@2.2.13          |         +2.19% |       (1,795,265 rps) |      (avg: 0.557μs) |
| **@typeofweb/schema** |        **ref** |   **(1,756,781 rps)** |  **(avg: 0.569μs)** |
| mschema@0.5.6         |        -69.22% |         (540,677 rps) |          (avg: 1μs) |
| validator.js@2.0.4    |        -76.78% |         (407,998 rps) |          (avg: 2μs) |
| validate.js@0.13.1    |        -87.21% |         (224,762 rps) |          (avg: 4μs) |
| validatorjs@3.22.1    |        -91.24% |         (153,877 rps) |          (avg: 6μs) |
| joi@17.3.0            |        -93.17% |         (120,062 rps) |          (avg: 8μs) |
| yup@0.32.8            |        -96.17% |          (67,263 rps) |         (avg: 14μs) |
| superstruct@0.13.3    |        -96.37% |          (63,762 rps) |         (avg: 15μs) |
| parambulator@1.5.2    |        -98.65% |          (23,649 rps) |         (avg: 42μs) |
| zod@1.11.11           |        -99.08% |          (16,099 rps) |         (avg: 62μs) |

**Comment by mmiszy** [comment]
Stats for v0.7.0:

```
Platform info:
==============
   Darwin 20.3.0 x64
   Node.JS: 14.16.0
   V8: 8.4.371.19-node.18
   Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz × 8
```

| library               | relative speed | operations per second | avg. operation time |
| --------------------- | -------------: | --------------------: | ------------------: |
| **@typeofweb/schema** |        **ref** |   **(1,934,098 rps)** |  **(avg: 0.517μs)** |
| io-ts@2.2.13          |         -7.21% |       (1,794,594 rps) |      (avg: 0.557μs) |
| mschema@0.5.6         |         -69.8% |         (584,151 rps) |          (avg: 1μs) |
| validator.js@2.0.4    |        -76.16% |         (461,088 rps) |          (avg: 2μs) |
| validate.js@0.13.1    |        -89.02% |         (212,408 rps) |          (avg: 4μs) |
| validatorjs@3.22.1    |         -92.2% |         (150,791 rps) |          (avg: 6μs) |
| joi@17.3.0            |        -93.25% |         (130,541 rps) |          (avg: 7μs) |
| superstruct@0.13.3    |        -96.99% |          (58,197 rps) |         (avg: 17μs) |
| yup@0.32.8            |        -97.09% |          (56,243 rps) |         (avg: 17μs) |
| parambulator@1.5.2    |        -98.99% |          (19,492 rps) |         (avg: 51μs) |
| zod@1.11.11           |        -99.03% |          (18,827 rps) |         (avg: 53μs) |

**Comment by mmiszy** [comment]
Created a PR: https://github.com/moltar/typescript-runtime-type-benchmarks/pull/585
